### PR TITLE
Slight problem with interval callback posting multiple saves on dynamic pages.

### PR DESCRIPTION
**Pull request by selrach**
Set up interval callback so that on dynamic pages where the form gets removed and replaced (with a different form), the autosave interval is cancelled. It is based on the selector used to set up the autosave. Essentially if the selector doesn't return any elements, we cancel the interval.  If the newly generated form has the same id, you will still get multiple autosaves to show up.

### CODE REVIEW

**Comment by kflorence** [comment]
Hey, thanks for bringing this up :) I've actually been planning for awhile now to rewrite this plugin as a jQuery widget which, among other things, would bring in a `destroy()` method that would do this for you. In the meantime, a more appropriate fix would be exposing the `stopInterval()` method, probably through event triggering.

**Comment by selrach** [comment]
My pleasure, i was confused as to why multiple requests were getting sent.

Makes sense to expose a method, however I couldn't figure out how to
get a handle to the autosave plugin to try and call something on that
object.  Leveraging a widget makes sense for that.  I'm definitely not
a JQuery/javascript expert...

One other thing I kind of had to hack in is that dynamically created
elements don't have the triggers to know when they have been changed.
I hijacked the "condition" element to find newly added inputs
(levering a "dynamic_data" class) and add them into the autosave
instance.  Hopefully with a widget it would be possible to call a
function to addInputs.

Thanks for the widget, its helped tremendously.

On Mon, Jun 25, 2012 at 7:13 PM, Kyle Florence
reply@reply.github.com
wrote:

**Comment by kflorence** [comment]
Yeah, the way the plugin is written makes accessing the inner functions pretty difficult. I had wanted to write this as a widget originally, but was talked out of it by the original plugin author who didn't want to add any additional dependencies, which is understandable, but at this point it seems like the right thing to do. I'm not a big fan of jQuery.ui in general, but I do like the development pattern that jQuery.ui.widget offers.

I'll keep this ticket open until I get that work done, since your hacks will probably be useful for others with similar issues.

**Comment by thomasfranz** [comment]
First of all thanks for the good plugin. 

I'm also having the issue that my save method gets called twice and would like to ask you how I can fix that or if you will fix it?
It happens, e.g. with the example.html content when I generate that same content dynamically with a template engine (scalate).
I also tried selrach's version and it shows the same behavior.

**Comment by thomasfranz** [comment]
I narrowed down the problem and worked around it, yet I'd like to share the solution with you.
It seems to be due to the way forms are processed by the autosave plugin and the markup for forms in bootstrap respectively. The problem seems to occur only when the form contains the element 'fieldset'.

This works as expected:

<form id="profile-form" name="profile-form" class="form-horizontal" >
                   
            <div class="control-group">
                <label class="control-label" for="input01">Name:</label>
                <div class="controls">
                    <input name="name" type="text" class="input-xlarge" id="input01" value="${session.user.name}">                    
                </div>
            </div>
        
</form>


However, when the fieldset element is not commented, the autosave code for the form is executed twice.

**Comment by kflorence** [comment]
Thanks Thomas. I'm in the process of rewriting the entire plugin as a jQuery widget. If the problem still exists after the rewrite, I'd like to find some way to incorporate it into the test suite.

**Comment by kflorence** [comment]
This has been fixed here: https://github.com/nervetattoo/jquery-autosave/pull/17

**Comment by agetha** [comment]
I want to know how to add dynamically created elements to the auto save instance? I read selrach's comment here. But still could not figure out. Can anyone show me the sample?

**Pull request closed without merging**
